In [9]:
import numpy as np

board = np.array([
    [0,0,0,2,6,0,7,0,1],
    [6,8,0,0,7,0,0,9,0],
    [1,9,0,0,0,4,5,0,0],
    [8,2,0,1,0,0,0,4,0],
    [0,0,4,6,0,2,9,0,0],
    [0,5,0,0,0,3,0,2,8],
    [0,0,9,3,0,0,0,7,4],
    [0,4,0,0,5,0,0,3,6],
    [7,0,3,0,1,8,0,0,0]

])

print("The unsolved board:\n")
print(board)
print("\n")

def find_empty(board):
    
    for i in range(9):
        for j in range(9):
            if board[i][j]==0:
                return [i,j]
    return None
            
def valid(board,num,pos):
    
    # checking Row
    for i in range(9):
        if board[pos[0]][i]==num and i!=pos[1]:
            return False
        
    # checking Column
    for i in range(9):
        if board[i][pos[1]]==num and i!=pos[0]:
            return False
        
    # Checking boxes
    x_box = pos[1]//3
    y_box= pos[0]//3
    
    for i in range(y_box*3, y_box*3+3):
        for j in range(x_box*3, x_box*3+3):
            if board[i][j]==num and [i,j]!=pos:
                return False      
            
    return True

def solve(board):
    
    find = find_empty(board)
    
    if not find:
        return True
    
    else:     
        row ,col =  find  
    
    for m in range(1,10):
        
        if valid(board,m, [row,col]):
            board[row][col]=m
            
            if solve(board):
                return True
            board[row][col]=0
            
    return False

solve(board)

print("The solved board:\n")
print(board)


The unsolved board:

[[0 0 0 2 6 0 7 0 1]
 [6 8 0 0 7 0 0 9 0]
 [1 9 0 0 0 4 5 0 0]
 [8 2 0 1 0 0 0 4 0]
 [0 0 4 6 0 2 9 0 0]
 [0 5 0 0 0 3 0 2 8]
 [0 0 9 3 0 0 0 7 4]
 [0 4 0 0 5 0 0 3 6]
 [7 0 3 0 1 8 0 0 0]]


The solved board:

[[4 3 5 2 6 9 7 8 1]
 [6 8 2 5 7 1 4 9 3]
 [1 9 7 8 3 4 5 6 2]
 [8 2 6 1 9 5 3 4 7]
 [3 7 4 6 8 2 9 1 5]
 [9 5 1 7 4 3 6 2 8]
 [5 1 9 3 2 6 8 7 4]
 [2 4 8 9 5 7 1 3 6]
 [7 6 3 4 1 8 2 5 9]]
